extends: "airbnb-base/legacy"
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules: {
  indent: [
      "error",
      4
  ],
  brace-style: [
      "error",
      "allman"
  ],
  quotes: [
      "error",
      "double",
    {
      avoidEscape: true
    }
  ],
  max-len: [
      "error",
      120
  ],
  func-names: [
      "warn",
      "never"
  ]
}
